project:
  type: website

website:
  title: "Fankai Dai"
  search: false
  page-navigation: true 
  navbar:
    left:
      - text: About
        href: index.html#about
      - text: Research
        href: index.html#research
      - text: Contact
        href: index.html#contact
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    # 这一行非常重要！防止 Quarto 给你的双栏布局加侧边栏干扰
    page-layout: full 
    # 配合顶栏跳转
    anchor-sections: true