project:
  type: website

website:
  title: "Fankai Dai"
  navbar:
    left:
      - text: About
        href: "#about"
      - text: Research
        href: "#research"
      - text: CV
        href: "#cv"

format:
  html:
    theme: cosmo
    toc: false



